import { Link } from "react-router-dom";

interface BlogCardProps {
  author?: string;
  title: string;
  content: string;
  createdAt: string;
  id: string; // unique identifier for the blog post, auto-generated by the server
}
const BlogCart = ({ author, title, content, createdAt, id }: BlogCardProps) => {
  return (
    <Link to={"/blog/" + id}>
      <div className="border-b-2 mt-2 border-slate-200 px-2 py-3 flex flex-col justify-center gap-2  w-[90vw]  sm:w-[56vw] ">
        <div className="flex gap-2 items-center">
          <div className="relative inline-flex items-center justify-center w-6 h-6 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
            <span className="font-medium text-gray-600 dark:text-gray-300">
              {author && author[0]}
            </span>
          </div>
          <div className=" font-semibold ">{author}</div>
          <div className="font-extralight pl-3 text-[13px]">
            {createdAt.split("-")[0]}
          </div>
        </div>
        <div className="sm:text-xl text-lg font-bold w-full">{title}</div>
        <div className="w-[90%] text-sm text-slate-700">
          {content.length > 100 ? content.slice(0, 100) + "..." : content}
        </div>
        <div className="text-slate-400 text-[13px]">{`${Math.ceil(
          content.length / 100
        )} minutes read `}</div>
      </div>
    </Link>
  );
};

export default BlogCart;
