import axios from "axios";
import { useEffect, useState } from "react";
import { BACKEND_URL } from "../config";
import { useParams } from "react-router-dom";
import FullBlog from "../components/FullBlog";
import Skeleton from "../components/Skeleton";
import AppBar from "../components/AppBar";

interface BlogCardProps {
  author?: {
    firstName?: string;
  };
  title: string;
  content: string;
  createdAt: string;
  // unique identifier for the blog post, auto-generated by the server
}
const Blog = () => {
  const { id } = useParams(); // replace with the actual blog ID
  // console.log(id);

  const [blog, setBlog] = useState<BlogCardProps>();
  const [loading, setLoading] = useState(true);
  // Fetch blogs from the server

  const fetchData = async () => {
    try {
      const posts = await axios.get(`${BACKEND_URL}/api/v1/blog/${id}`, {
        headers: {
          Authorization: localStorage.getItem("token") || "",
        },
      });
      setBlog(posts.data.posts);
      console.log(blog);
    } catch (error) {
      console.error("Error fetching data:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [id]);
  if (loading) return <Skeleton />;
  return (
    <>
      <AppBar />
      <FullBlog
        author={{ fullName: blog?.author?.firstName || "Anonymous" }}
        title={blog?.title}
        content={blog?.content}
        createdAt={blog?.createdAt}
      />
    </>
  );
};

export default Blog;
